- hosts: controller
  user: root
  tasks:
    - name: Download and install RDO repository
      yum:
        name: https://rdoproject.org/repos/rdo-release.rpm
        state: present

    - name: Install centos-release-openstack-ocata
      yum:
        name: centos-release-openstack-ocata
        state: latest

    - name: Update package from yum
      yum:
        name: '*'
        state: latest

    - name: Install openstack-packstack
      yum:
        name: openstack-packstack
        state: latest

    - name: Get the packstack answer-file from GitHub
      git:
        repo: https://github.com/tatsuyaTo/packstack.git
        dest: /tmp/checkout
        version: ocata
        force: yes

    - name: Install OpenStack with PackStack
      command: packstack --allinone

