- hosts: targets
  user: root
  tasks:
    - name: update packages from yum
      yum: name=* state=latest

    - name: install packages from yum
      yum: name={{ item }} state=latest
      with_items:
        - openstack-utils

